import moment from "moment";

export const CALENDAR_INITIAL_EVENTS = Object.freeze([
  {
    title: "Product call",
    theme: "GREEN",
    startTime: moment().add(-12, "d").startOf("day").toISOString(),
    endTime: moment().add(-12, "d").endOf("day").toISOString(),
  },
  {
    title: "Meeting with tech team",
    theme: "PINK",
    startTime: moment().add(-8, "d").startOf("day").toISOString(),
    endTime: moment().add(-6, "d").endOf("day").toISOString(),
  }, // 3-day event
  {
    title: "Meeting with Cristina",
    theme: "PURPLE",
    startTime: moment().add(-2, "d").startOf("day").toISOString(),
    endTime: moment().add(-1, "d").endOf("day").toISOString(),
  }, // 2-day event
  {
    title: "Meeting with Alex",
    theme: "BLUE",
    startTime: moment().startOf("day").toISOString(),
    endTime: moment().add(1, "d").endOf("day").toISOString(),
  }, // 2-day event
  {
    title: "Product Call",
    theme: "GREEN",
    startTime: moment().startOf("day").toISOString(),
    endTime: moment().endOf("day").toISOString(),
  },
  {
    title: "Client Meeting",
    theme: "PURPLE",
    startTime: moment().startOf("day").toISOString(),
    endTime: moment().endOf("day").toISOString(),
  },
  {
    title: "Client Meeting",
    theme: "ORANGE",
    startTime: moment().add(3, "d").startOf("day").toISOString(),
    endTime: moment().add(5, "d").endOf("day").toISOString(),
  }, // 3-day event
  {
    title: "Product meeting",
    theme: "PINK",
    startTime: moment().add(5, "d").startOf("day").toISOString(),
    endTime: moment().add(5, "d").endOf("day").toISOString(),
  },
  {
    title: "Sales Meeting",
    theme: "GREEN",
    startTime: moment().add(8, "d").startOf("day").toISOString(),
    endTime: moment().add(9, "d").endOf("day").toISOString(),
  }, // 2-day event
  {
    title: "Product Meeting",
    theme: "ORANGE",
    startTime: moment().add(8, "d").startOf("day").toISOString(),
    endTime: moment().add(8, "d").endOf("day").toISOString(),
  },
  {
    title: "Marketing Meeting",
    theme: "PINK",
    startTime: moment().add(8, "d").startOf("day").toISOString(),
    endTime: moment().add(10, "d").endOf("day").toISOString(),
  }, // 3-day event
  {
    title: "Client Meeting",
    theme: "GREEN",
    startTime: moment().add(8, "d").startOf("day").toISOString(),
    endTime: moment().add(9, "d").endOf("day").toISOString(),
  }, // 2-day event
  {
    title: "Sales meeting",
    theme: "BLUE",
    startTime: moment().add(12, "d").startOf("day").toISOString(),
    endTime: moment().add(14, "d").endOf("day").toISOString(),
  }, // 3-day event
  {
    title: "Client meeting",
    theme: "PURPLE",
    startTime: moment().add(16, "d").startOf("day").toISOString(),
    endTime: moment().add(17, "d").endOf("day").toISOString(),
  }, // 2-day event
]);

export const RECENT_TRANSACTIONS = Object.freeze([
  {
    name: "Alex",
    avatar: "https://reqres.in/img/faces/1-image.jpg",
    email: "alex@BrandWind.com",
    location: "Paris",
    amount: 100,
    date: moment().endOf("day"),
    status: "paid",
  },
  {
    name: "Ereena",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
    email: "ereena@BrandWind.com",
    location: "London",
    amount: 190,
    date: moment().add(-1, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "John",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "jhon@BrandWind.com",
    location: "Canada",
    amount: 112,
    date: moment().add(-1, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Matrix",
    avatar: "https://reqres.in/img/faces/4-image.jpg",
    email: "matrix@BrandWind.com",
    location: "Peru",
    amount: 111,
    date: moment().add(-1, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Virat",
    avatar: "https://reqres.in/img/faces/5-image.jpg",
    email: "virat@BrandWind.com",
    location: "London",
    amount: 190,
    date: moment().add(-2, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Miya",
    avatar: "https://reqres.in/img/faces/6-image.jpg",
    email: "miya@BrandWind.com",
    location: "Paris",
    amount: 230,
    date: moment().add(-2, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Virat",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "virat@BrandWind.com",
    location: "Canada",
    amount: 331,
    date: moment().add(-2, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Matrix",
    avatar: "https://reqres.in/img/faces/1-image.jpg",
    email: "matrix@BrandWind.com",
    location: "London",
    amount: 581,
    date: moment().add(-2, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Ereena",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "ereena@BrandWind.com",
    location: "Tokyo",
    amount: 151,
    date: moment().add(-2, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "John",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
    email: "jhon@BrandWind.com",
    location: "Paris",
    amount: 91,
    date: moment().add(-2, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Virat",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "virat@BrandWind.com",
    location: "Canada",
    amount: 161,
    date: moment().add(-3, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Matrix",
    avatar: "https://reqres.in/img/faces/4-image.jpg",
    email: "matrix@BrandWind.com",
    location: "US",
    amount: 121,
    date: moment().add(-3, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Ereena",
    avatar: "https://reqres.in/img/faces/6-image.jpg",
    email: "jhon@BrandWind.com",
    location: "Tokyo",
    amount: 713,
    date: moment().add(-3, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "John",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
    email: "ereena@BrandWind.com",
    location: "London",
    amount: 217,
    date: moment().add(-3, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Virat",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "virat@BrandWind.com",
    location: "Paris",
    amount: 117,
    date: moment().add(-3, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Miya",
    avatar: "https://reqres.in/img/faces/7-image.jpg",
    email: "jhon@BrandWind.com",
    location: "Canada",
    amount: 612,
    date: moment().add(-3, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Matrix",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "matrix@BrandWind.com",
    location: "London",
    amount: 631,
    date: moment().add(-3, "d").endOf("day"),
    status: "paid",
  },
  {
    name: "Virat",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
    email: "ereena@BrandWind.com",
    location: "Tokyo",
    amount: 151,
    date: moment().add(-3, "d").endOf("day"),
    status: "pending",
  },
  {
    name: "Ereena",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "virat@BrandWind.com",
    location: "Paris",
    amount: 617,
    date: moment().add(-3, "d").endOf("day"),
    status: "paid",
  },
]);

export const NOTIFICATIONS = Object.freeze([
  {
    id: 1,
    message: "Your sales has increased by 30% yesterday",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 2,
    message:
      "Total likes for Instagram post - New launch this week, has crossed 100k",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 3,
    message: "Server restarted successfully",
    date: new Date().toISOString(),
    seen: true,
  },
  {
    id: 4,
    message: "New user signed up",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 5,
    message: "Your sales has increased by 30% yesterday",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 6,
    message:
      "Total likes for Instagram post - New launch this week, has crossed 100k",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 7,
    message: "Server restarted successfully",
    date: new Date().toISOString(),
    seen: true,
  },
  {
    id: 8,
    message: "New user signed up",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 9,
    message: "Your sales has increased by 30% yesterday",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 10,
    message:
      "Total likes for Instagram post - New launch this week, has crossed 100k",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 11,
    message: "Server restarted successfully",
    date: new Date().toISOString(),
    seen: true,
  },
  {
    id: 12,
    message: "New user signed up",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 13,
    message: "Your sales has increased by 30% yesterday",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 14,
    message:
      "Total likes for Instagram post - New launch this week, has crossed 100k",
    date: new Date().toISOString(),
    seen: false,
  },
  {
    id: 15,
    message: "Server restarted successfully",
    date: new Date().toISOString(),
    seen: true,
  },
  {
    id: 16,
    message: "New user signed up",
    date: new Date().toISOString(),
    seen: false,
  },
]);

export const TEAM_INITIAL_MEMBERS = Object.freeze([
  {
    id: 1,
    name: "Alex Johnson",
    avatar: "https://reqres.in/img/faces/1-image.jpg",
    email: "alex@BrandWind.com",
    role: "Owner",
    joinedOn: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastActive: "2 hr ago",
  },
  {
    id: 2,
    name: "Ereena Smith",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
    email: "ereena@BrandWind.com",
    role: "Admin",
    joinedOn: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    lastActive: "15 min ago",
  },
  {
    id: 3,
    name: "John Doe",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
    email: "john@BrandWind.com",
    role: "Manager",
    joinedOn: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    lastActive: "1 hr ago",
  },
  {
    id: 4,
    name: "Matrix Lee",
    avatar: "https://reqres.in/img/faces/4-image.jpg",
    email: "matrix@BrandWind.com",
    role: "Support",
    joinedOn: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    lastActive: "30 min ago",
  },
  {
    id: 5,
    name: "Miya Patel",
    avatar: "https://reqres.in/img/faces/6-image.jpg",
    email: "miya@BrandWind.com",
    role: "Support",
    joinedOn: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    lastActive: "3 hr ago",
  },
]);
