export const MODAL_BODY_TYPES = Object.freeze({
  CONFIRMATION: 'CONFIRMATION',
  FEEDBACK: 'FEEDBACK',
  EVENT: 'EVENT',
  LEAD_ADD_NEW: 'LEAD_ADD_NEW',
  INVITE_MEMBER: 'INVITE_MEMBER',
  DEFAULT: '',
});

export const RIGHT_DRAWER_TYPES = Object.freeze({
  NOTIFICATION: 'NOTIFICATION',
  CONSULTATION: 'CONSULTATION',
  CALENDAR_EVENTS: 'EVENTS',
});

export const CONFIRMATION_MODAL_CLOSE_TYPES = {};
